### PR TITLE
potential fix for key mismatch in issue #40

### PR DESCRIPTION
**Pull request by fluidmotion**
- relating pilot point names to factors in geostats.py

### CODE REVIEW

**Comment by jtwhite79** [comment]
This PR fails all of the fac2real related tests, including the verification tests against the pest uitls = frowny face...Let's see if we can get your case going, then we can revisit refactoring the fac2real function to use the actual names of the pilot points.  I'm just worried about the additional level of indirection: factor index -> pp index -> pp name -> pp value; this function is already slow compared to the compiled version...

**Comment by fluidmotion** [comment]
ugh. just saw that. oops. i believe the pilots and the factors are listed in the same order, but the factors appear to begin with 1? whereas the pilots use a feature ID from a subset of a GIS file (starting at 17334). i suppose the subset can be reset to one-based, just didn't realize the need.

**Comment by jtwhite79** [comment]
The factors are 1-based but internally, pyemu converts that zero-based (the real base!), so you prob want to have a zero-based index on the subset...

**Comment by fluidmotion** [comment]
ah - i didn't see this 
`pp_dict = {name:val for name,val in zip(pp_data.index,pp_data.parval1)}` 
where the pp_dict key is the index, rather than the 'name' column.
sorry for the trouble. closing.

**Pull request closed without merging**
